{
 "title": "Epever",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Pannelli Fotovoltaici", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pannelli WATT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "epever_pvWatt", "legendFormat": "PV Watt " }
   ]
  },
  {
   "title": "Pannelli VOLT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "epever_pvVolt", "legendFormat": "PV Volt" }
   ]
  },
  {
   "title": "Pannelli AMPERE",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "epever_pvAmpere", "legendFormat": "PV Ampere" }
   ]
  },
  {
   "title": "Giorno / Notte",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "epever_dayNight", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Over Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "epever_overTemp", "legendFormat": "__auto" }
   ]
  },
  { "title": "Batterie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Batterie VOLT",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "epever_battVolt", "legendFormat": "Volt Batterie" },
    { "expr": "epever_battRatedVolt", "legendFormat": "Volt Batterie" }
   ]
  },
  {
   "title": "Batterie AMPERE",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "epever_battAmpere", "legendFormat": "Volt Batterie" }
   ]
  },
  {
   "title": "Batterie Stato Carica",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "epever_battSOC", "legendFormat": "Volt Batterie" }
   ]
  },
  {
   "title": "Modalità di carica",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "epever_chargeEquipStatusChargingStatus",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batterie TEMP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "epever_battTemp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batteria Wrong Identification",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "epever_battWrongIdentification", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batteria Voltage Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "epever_battTempStat", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batteria Internal Resistance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "epever_battWrongIdentification", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batteria Temperature Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "epever_battTempStat", "legendFormat": "__auto" }
   ]
  },
  { "title": "Carico", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Carico VOLT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "epever_loadVolt", "legendFormat": "Volt Batterie" },
    { "expr": "epever_battRatedVolt", "legendFormat": "Volt Batterie" }
   ]
  },
  {
   "title": "Carico AMPERE",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "epever_loadAmpere", "legendFormat": "Carico Ampere" }
   ]
  },
  {
   "title": "Carico WATT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "epever_loadWatt", "legendFormat": "PV Ampere" }
   ]
  }
 ]
}